In [5]:
import os
import numpy as np
import json
import glob
from loaddata import loaddata
import cv2



f = open('../results/week5/standard-parameters-results.json')
h = json.load(f)


par = ['bag','lr', 'depth', 'batch', 'rounds']
n_samples=[]
n_features=[]
hyperparameters={k:[] for k in par}


for k,v in h.items():
    

    (x_train0, y_train), (x_test0, y_test) = loaddata(k)
    samples = x_test0.shape[0]
    features = x_test0.shape[1]

    n_samples.append(samples)
    n_features.append(features)

    img1 = cv2.imread("Path to image 1",0)
    img2 = cv2.imread("Path to image 2",0)




In [6]:
h

{'fashion0': 0.8863260000000001,
 'har': 0.9066469498854779,
 'Liver_1': 0.5137912385073012,
 'pima': 0.6386222222222222,
 'breastw': 0.9531347164904743,
 'cover': 0.6349186702533751,
 'steel-plates-fault': 0.6116666666666666,
 'optdigits': 0.9155555555555556,
 'Diabetes_present': 0.6218666666666667,
 'wbc': 0.9727891156462586}

In [16]:
import scipy.spatial as sp
a = 1 - sp.distance.cdist(mat, tam, 'cosine')

array([[1.        , 0.98386991],
       [0.98386991, 1.        ]])

In [58]:
mat = np.array([[1,2,3], [1,4,5]])
mat

array([[1, 2, 3],
       [1, 4, 5]])

In [59]:
tam = np.array([[1,2,10], [3,-4,2], [0,0,0]])
tam

array([[ 1,  2, 10],
       [ 3, -4,  2],
       [ 0,  0,  0]])